# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/tyrantkhan/bitbucket-cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v0.0.2/bb_0.0.2_darwin_amd64.tar.gz"
      sha256 "634c76c5d4ea428595e65dd864f2e45b094ef0973177956692e7263ad6903f47"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v0.0.2/bb_0.0.2_darwin_arm64.tar.gz"
      sha256 "5633f25693e9464b663088ae315f1f7a4fa7e3b6834546d89d6408c598c1ddd6"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v0.0.2/bb_0.0.2_linux_amd64.tar.gz"
      sha256 "93c5e91e1a9ad817cd7be566f8970606e2a18e8b1f8b665a5500d003df3cb429"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v0.0.2/bb_0.0.2_linux_arm64.tar.gz"
      sha256 "538f2760d8a7c2f5b1c6618c0f6e72e8ebb06d48e23122b890062a84d31b4222"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--version"
  end
end
