# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  name "bb"
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/tyrantkhan/bitbucket-cli"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  on_macos do
    on_intel do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "014e007e149376089bf9bb2a4823b6281992dcf0b8f84823345b41404cd14bf2"
    end
    on_arm do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "bdbf6c459b7e2276e2e010b5183386db4401c931f29cf262fde9e42c5c755414"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "eac59250ec39c4d619023691af90aa39403e3c0451cb7f3f427562a12b5cd274"
    end
    on_arm do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "483f348b424a34684b95d293f4cd49f5209b98d36b7d908f47c17c631a10fbe4"
    end
  end

  # No zap stanza required
end
