# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  name "bb"
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/tyrantkhan/bitbucket-cli"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  on_macos do
    on_intel do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "e1850e1b6b7e0ab01a90d24634baf9ac6056e07635f6a71ae76480b293eca0f9"
    end
    on_arm do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "2e1b111f501170f2886674eca880ebb31dc9ff4a56c54b7716f70165ec3bf7ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "598038c9a1c3d9a5cb95d5366ef45450894e009663af5064cb0bf10488b1fb33"
    end
    on_arm do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "4a3cb2e774250483dfd102bfbf6b646e23a7de51eea2547f57f4a672051ef826"
    end
  end

  # No zap stanza required
end
