# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  name "bb"
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/tyrantkhan/bitbucket-cli"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  on_macos do
    on_intel do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "4c6522581168f6c53efe899913d860a7fd15da9a927ba8cda235ea9f3de96aaa"
    end
    on_arm do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "8ef6b03867a9ae880a69174358fa7242e861ae76140c0c7fb4acae0337f23d5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "5a02d5232f1a46b2073555501c63a4497ef7f5cc3a3cfab3bb31a11c0dfe1069"
    end
    on_arm do
      url "https://github.com/tyrantkhan/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tyrantkhan/bitbucket-cli/"
      sha256 "8be3190e831416abf33f4b6ea6b7935ae9503958a863f4fb68ef72b1cdb18a1e"
    end
  end

  # No zap stanza required
end
